# Generated by Django 3.1.14 on 2022-03-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='pages_team',
        ),
    ]
