# Generated by Django 3.1.14 on 2022-03-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220302_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pages_team',
            new_name='Team',
        ),
    ]
